# source_id:
#   name: value
#   description: value
#   link: value
#   update_rate: value
#   extraction_date: value

# csvs:
#   sources:
#     - source_id
#     - name
#     - description
#     - link
#     - update_rate
#     - extraction_date

datasus_cnes:
  name: Cadastro Nacional de Estabelecimentos de Saúde
  description: Dados de instituições de saúde do DATASUS
  link: http://cnes.datasus.gov.br/pages/downloads/arquivosBaseDados.jsp
  update_rate: Mensal
  extraction_date: '2020-10-01'

datasus_geo:
  name: Território DATASUS
  description: Dados de territórios do DATASUS
  link: ftp://ftp.datasus.gov.br/territorio/tabelas
  update_rate: Anual
  extraction_date: '2020-10-01'

datasus_population:
  name: População DATASUS
  description: Estimativas de dados populacionais do DATASUS
  link: http://tabnet.datasus.gov.br/cgi/deftohtm.exe?popsvs/cnv/popbr.def
  update_rate: Anual
  extraction_date: '2020-10-01'

datasus_sinasc:
  name: Sistema de informação de Nascidos Vivos
  description: Registros de nascidos vivos do DATASUS
  link: http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1
  update_rate: Anual
  extraction_date: '2020-10-01'

iso_3166:
  name: ISO 3166
  description: Códigos de países
  link: https://www.iso.org/iso-3166-country-codes.html
  update_rate: Esporádico
  extraction_date: '2020-10-01'

datasus_sinan:
  name: Sistema de agravos de notificação compulsória
  description: Dados de notificação/ocorrência e investigação de doenças e agravos de notificação compulsória
  link: ftp://ftp.datasus.gov.br/dissemin/publicos/SINAN/DADOS/FINAIS/
  update_rate: Anual
  extraction_date: '2020-11-04'

datasus_sim:
  name: Sistema de Informações sobre Mortalidade
  description: Dados de mortalidade
  link: http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1&acao=26&pad=31655
  update_rate: Anual
  extraction_date: '2020-11-02'

tabnet_sipni:
  name: Sistema de Informações do Programa Nacional de Imunizações - Cobertura vacinal
  description: Dados consolidados de cobertura vacinal
  link: http://tabnet.datasus.gov.br/cgi/dhdat.exe?bd_pni/cpnibr.def
  uptade_rate: Anual
  extraction_date: '2020-11-25'

datasus_sihsus:
  name: Sistema de informações hospitalares do SUS
  description: Dados consolidados de cobertura vacinal
  link: ftp://ftp.datasus.gov.br/dissemin/publicos/SIHSUS/
  uptade_rate: Mensal
  extraction_date: '2020-11-19'
